[font.normal]
family = "Monaspace Neon"

[window]
opacity = 0.8

dimensions = { columns = 150, lines = 40 }

padding = { x = 8, y = 4 }

position = { x = 500, y = 300 }

[scrolling]
history = 10000

# https://github.com/alacritty/alacritty-theme
# https://github.com/alacritty/alacritty-theme/blob/master/themes/seashells.toml
[colors.primary]
background = '#061923'
foreground = '#e5c49e'

[colors.cursor]
text = '#061822'
cursor = '#feaf3c'

[colors.selection]
text = '#ffe9d7'
background = '#265b75'

[colors.normal]
black = '#1d485f'
red = '#db662d'
green = '#008eab'
yellow = '#feaf3c'
blue = '#255a62'
magenta = '#77dbf4'
cyan = '#5fb1c2'
white = '#e5c49e'

[colors.bright]
black = '#545d65'
red = '#dd998a'
green = '#739da8'
yellow = '#fedaae'
blue = '#0bc7e3'
magenta = '#c6e8f1'
cyan = '#97b9c0'
white = '#ffe9d7'

