[font.normal]
family = "Monaspace Neon"

[font]
size = 12.5

[window]
opacity = 0.95

dimensions = { columns = 150, lines = 40 }

padding = { x = 8, y = 4 }

position = { x = 500, y = 300 }

[scrolling]
history = 10000

# https://github.com/alacritty/alacritty-theme
# https://github.com/alacritty/alacritty-theme/blob/master/themes/github_dark.toml
# github Alacritty Colors

# Default colors
[colors.primary]
background = '#24292e'
foreground = '#d1d5da'

# Normal colors
[colors.normal]
black   = '#586069'
red     = '#ea4a5a'
green   = '#34d058'
yellow  = '#ffea7f'
blue    = '#2188ff'
magenta = '#b392f0'
cyan    = '#39c5cf'
white   = '#d1d5da'

# Bright colors
[colors.bright]
black   = '#959da5'
red     = '#f97583'
green   = '#85e89d'
yellow  = '#ffea7f'
blue    = '#79b8ff'
magenta = '#b392f0'
cyan    = '#56d4dd'
white   = '#fafbfc'

[[colors.indexed_colors]]
index = 16
color = '#d18616'

[[colors.indexed_colors]]
index = 17
color = '#f97583'

