set nu
set ruler
set title
set virtualedit=block
set nosmartindent
set t_Co=256
set autoindent
set showmatch
set list
set listchars=tab:>-,extends:<,trail:-,eol:<
set laststatus=2
set softtabstop=4
set shiftwidth=4
set noundofile
set noswapfile
set nobackup