alias ltr 'ls -ltr'
alias tree 'tree -NC'
alias gst 'git status'
alias gdf 'git diff --color-words'
alias gcm 'git checkout master'
alias gc 'git checkout -'
alias gpu 'git pull upstream master'
alias glog 'git log --oneline'
alias dcu 'docker-compose up'
alias dcd 'docker-compose down'
alias dcr 'docker-compose run --rm'
alias dpa 'docker ps -a'
alias dpurge 'docker stop (docker ps -aq) && docker rm (docker ps -aq)'
