alias ltr 'ls -ltr'
alias tree 'tree -NC'
alias gst 'git status'
alias gdf 'git diff --color-words'
alias gcm 'git checkout master'
alias gc 'git checkout -'
alias gpu 'git pull upstream master'
alias hub 'hub checkout'
alias dpurge 'docker stop (docker ps -aq) && docker rm (docker ps -aq)'
