add_newline = false

[package]
disabled = true

[cmd_duration]
disabled = true

[line_break]
disabled = true

[directory]
truncation_length = 10
truncate_to_repo  = false

[git_branch]
symbol = ''


[git_status]
untracked = "U"
modified  = "M"
deleted   = "D"
staged    = '[++\($count\)](green)'

[golang]
disabled = true

[nodejs]
disabled = true

[python]
disabled = true

[ruby]
disabled = true

[terraform]
disabled = true

[deno]
disabled = true

[buf]
disabled = true

[docker_context]
disabled = true

[rust]
disabled = true
