---
  - name: brew update
    community.general.homebrew:
      update_homebrew: yes

  - name: brew install packages
    community.general.homebrew:
      name: '{{ item }}'
    loop: '{{ brew_packages }}'

  - name: brew install packages (not development)
    community.general.homebrew:
      name: '{{ item }}'
    loop: '{{ brew_packages_not_development }}'
    when: not_development
