---
  - name: brew update & upgrade
    community.general.homebrew:
      update_homebrew: true
      upgrade_all: true

  - name: brew install packages
    community.general.homebrew:
      name: '{{ item }}'
    loop: '{{ brew_packages }}'

  - name: brew install job packages
    community.general.homebrew:
      name: '{{ item }}'
    loop: '{{ brew_job_packages }}'
    when: job

  - name: brew install extra packages
    community.general.homebrew:
      name: '{{ item }}'
    loop: '{{ brew_extra_packages }}'
    when: extra
